// flow-typed signature: c3eca676fb7683e98728d5c3db11cfa6
// flow-typed version: <<STUB>>/babel-project-relative-import_v^2.0.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-project-relative-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-project-relative-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-project-relative-import/dist/plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-project-relative-import/dist/plugin.js' {
  declare module.exports: $Exports<'babel-project-relative-import/dist/plugin'>;
}
