// flow-typed signature: 557d468d38c9fc147ea7772641e33b4a
// flow-typed version: <<STUB>>/lowdb_v^0.14.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lowdb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'lowdb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lowdb/dist/lowdb' {
  declare module.exports: any;
}

declare module 'lowdb/dist/lowdb.min' {
  declare module.exports: any;
}

declare module 'lowdb/lib/_index' {
  declare module.exports: any;
}

declare module 'lowdb/lib/browser' {
  declare module.exports: any;
}

declare module 'lowdb/lib/file-async' {
  declare module.exports: any;
}

declare module 'lowdb/lib/file-sync' {
  declare module.exports: any;
}

declare module 'lowdb/lib/index.browser' {
  declare module.exports: any;
}

declare module 'lowdb/lib/index.node' {
  declare module.exports: any;
}

declare module 'lowdb/lib/json' {
  declare module.exports: any;
}

declare module 'lowdb/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lowdb/dist/lowdb.js' {
  declare module.exports: $Exports<'lowdb/dist/lowdb'>;
}
declare module 'lowdb/dist/lowdb.min.js' {
  declare module.exports: $Exports<'lowdb/dist/lowdb.min'>;
}
declare module 'lowdb/lib/_index.js' {
  declare module.exports: $Exports<'lowdb/lib/_index'>;
}
declare module 'lowdb/lib/browser.js' {
  declare module.exports: $Exports<'lowdb/lib/browser'>;
}
declare module 'lowdb/lib/file-async.js' {
  declare module.exports: $Exports<'lowdb/lib/file-async'>;
}
declare module 'lowdb/lib/file-sync.js' {
  declare module.exports: $Exports<'lowdb/lib/file-sync'>;
}
declare module 'lowdb/lib/index.browser.js' {
  declare module.exports: $Exports<'lowdb/lib/index.browser'>;
}
declare module 'lowdb/lib/index.node.js' {
  declare module.exports: $Exports<'lowdb/lib/index.node'>;
}
declare module 'lowdb/lib/json.js' {
  declare module.exports: $Exports<'lowdb/lib/json'>;
}
declare module 'lowdb/webpack.config.js' {
  declare module.exports: $Exports<'lowdb/webpack.config'>;
}
