// flow-typed signature: b2d77b18e7a5502e6bb445fe9f91a9ec
// flow-typed version: <<STUB>>/session_v^0.1.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'session'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'session' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'session/lib/session/index' {
  declare module.exports: any;
}

declare module 'session/lib/session/session' {
  declare module.exports: any;
}

declare module 'session/lib/session/storage/base' {
  declare module.exports: any;
}

declare module 'session/lib/session/storage/memcached' {
  declare module.exports: any;
}

declare module 'session/lib/session/storage/memory' {
  declare module.exports: any;
}

declare module 'session/test/session/session.test' {
  declare module.exports: any;
}

declare module 'session/test/session/storage/base.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'session/lib/session/index.js' {
  declare module.exports: $Exports<'session/lib/session/index'>;
}
declare module 'session/lib/session/session.js' {
  declare module.exports: $Exports<'session/lib/session/session'>;
}
declare module 'session/lib/session/storage/base.js' {
  declare module.exports: $Exports<'session/lib/session/storage/base'>;
}
declare module 'session/lib/session/storage/memcached.js' {
  declare module.exports: $Exports<'session/lib/session/storage/memcached'>;
}
declare module 'session/lib/session/storage/memory.js' {
  declare module.exports: $Exports<'session/lib/session/storage/memory'>;
}
declare module 'session/test/session/session.test.js' {
  declare module.exports: $Exports<'session/test/session/session.test'>;
}
declare module 'session/test/session/storage/base.test.js' {
  declare module.exports: $Exports<'session/test/session/storage/base.test'>;
}
